#!/bin/sh /etc/rc.common
START=90

PROG=/usr/sbin/log2drop.sh
SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1


# Yes the grep regexp is hideous
getKids() { 
 grep -e "^PPid:$(printf '\t')*$1$" /proc/[0-9]*/status 2>/dev/null | cut -f3 -d/ | xargs echo
}

start() {
	echo "Starting log2drop"
        service_start "${PROG}" -m follow
}

stop() {
        PID=$(cat /var/run/log2drop.sh.pid)
	echo "Stopping log2drop $PID"
	kill $(getKids "$PID")
	sleep 1
        service_stop "${PROG}"
}
